name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install NPM packages
        run: npm install
      - name: Run Biome
        run: npx biome check

  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install NPM packages
        run: npm install
      - name: Check TypeScript types
        run: npm run --prefix frontend check-types

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install NPM packages
        run: npm install
      - name: Install Playwright browsers and dependencies
        run: npx playwright install --with-deps
      - name: Run frontend tests
        run: npm run test-frontend
